CREATE TABLE IF NOT EXISTS redirects (
  id SERIAL PRIMARY KEY,
  source VARCHAR(255) NOT NULL,
  destination VARCHAR(255) NOT NULL,
  permanent BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS views (
  slug VARCHAR(255) PRIMARY KEY,
  count INT NOT NULL
);
