const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');
const envLocalPath = path.join(root, '.env.local');
const examplePath = path.join(root, '.env.example');

if (fs.existsSync(envLocalPath)) {
  console.log('✅ .env.local already exists. Skipping creation.');
  process.exit(0);
}

// Start with example contents if available
let out = '';
if (fs.existsSync(examplePath)) {
  const example = fs.readFileSync(examplePath, 'utf8');
  out += `# Generated by scripts/ensure-env.js\n`;
  out += `# Values are safe placeholders for local dev.\n\n`;

  // Very light transform: keep keys, fill known safe defaults
  const lines = example.split(/\r?\n/);
  for (const line of lines) {
    if (!line || line.trim().startsWith('#')) {
      out += `${line}\n`;
      continue;
    }
    const [key] = line.split('=');
    switch (key) {
      case 'DATABASE_URL':
      case 'DATABASE_URL_NON_POOLING':
        // Leave empty so DB-backed routes can be avoided in dev
        out += `${key}=""\n`;
        break;
      case 'NEXT_PUBLIC_GET_IN_TOUCH':
      case 'RESEND_SECRET':
      case 'NEXT_PUBLIC_TURNSTILE_SITE_KEY':
      case 'TURNSTILE_SECRET_KEY':
        out += `${key}=""\n`;
        break;
      default:
        out += `${line}\n`;
    }
  }
} else {
  // Minimal set if example is missing
  out =
    `# Generated by scripts/ensure-env.js\n` +
    `DATABASE_URL=""\n` +
    `DATABASE_URL_NON_POOLING=""\n` +
    `NEXT_PUBLIC_GET_IN_TOUCH=""\n` +
    `RESEND_SECRET=""\n` +
    `# Cloudflare Turnstile (contact form protection)\n` +
    `NEXT_PUBLIC_TURNSTILE_SITE_KEY=""\n` +
    `TURNSTILE_SECRET_KEY=""\n`;
}

fs.writeFileSync(envLocalPath, out, 'utf8');
console.log('✅ Created .env.local with safe defaults.');
