name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Download previous CV from releases (fallback)
      run: |
        mkdir -p public/files/
        # Try to download the latest CV from GitHub releases
        curl -L -o public/files/cv.pdf \
          "https://github.com/${{ github.repository }}/releases/latest/download/cv.pdf" \
          || echo "No previous CV release found, will generate new one"
    
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build CV from LaTeX
      run: npm run build-cv
    
    - name: Verify CV exists
      run: |
        if [ ! -f "public/files/cv.pdf" ]; then
          echo "Error: CV PDF not generated and no fallback available"
          exit 1
        fi
        echo "CV PDF verified: $(ls -la public/files/cv.pdf)"
    
    - name: Build Next.js application
      run: npm run build-only
    
    - name: Upload CV artifact for future builds
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: public/files/cv.pdf
        retention-days: 90
      
    - name: Create/Update CV Release
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: cv-latest
        name: "Latest CV"
        body: "Auto-generated CV from LaTeX source"
        files: public/files/cv.pdf
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}