name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'
    
    - name: Install LaTeX
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-base texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build CV from LaTeX
      run: npm run build-cv
    
    - name: Build Next.js application
      run: npm run build-only
    
    - name: Upload CV artifact
      uses: actions/upload-artifact@v4
      with:
        name: cv-pdf
        path: public/files/cv.pdf
        retention-days: 30