name: E2E (Playwright) on Vercel Preview

on:
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
      statuses: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Deploy to Vercel (Preview)
        id: vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: .
          github-comment: false
          github-deployment: true
          scope: ${{ secrets.VERCEL_ORG_ID }}

      - name: Log resolved Preview URL
        run: |
          echo "VERCEL_ENV=${{ steps.vercel.outputs.vercel-url && 'preview' || 'unknown' }}"
          echo "vercel.outputs.preview-url=${{ steps.vercel.outputs.preview-url }}"

      - name: Run Playwright against Preview
        env:
          E2E_BASE_URL: ${{ steps.vercel.outputs.preview-url }}
        run: npm run e2e:vercel

